---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: attestation-self-signed-issuer
  namespace: trustee-operator-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  selfSigned: {}
