{{- if and (ne .Values.global.secretStore.backend "none") (eq .Values.global.coco.securityPolicyFlavour "signed") }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata: 
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: cosigned-eso
  namespace: trustee-operator-system
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  data:
  target:
    name: cosign-keys
    template:
      type: generic
  dataFrom:
  - extract:
      key: {{ .Values.global.coco.cosignKeys }}
{{- end }}