---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata: 
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: pcrs-eso
  namespace: trustee-operator-system
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  data:
  target:
    name: pcr-stash
    template:
      type: generic
  dataFrom:
  - extract:
      key: 'secret/data/hub/pcrStash'
