apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: rvps-reference-values
  namespace: trustee-operator-system
data:
  reference-values.json: |
      [
      ]

