apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-policy
  namespace: trustee-operator-system
data:
  policy.rego: |
    package policy
    default allow = true
    
    allow {
      input["submods"]["cpu0"]["ear.status"] == "affirming"
    }