apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-policy
  namespace: trustee-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "4"
data:
  policy.rego: |
    package policy
    default allow = false
    allow {
      input["submods"]["cpu0"]["ear.status"] == "affirming"
    }