{{ if eq .Values.global.coco.secured  true }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: rvps-policy
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: rvps-policy-cp
      spec:
        remediationAction: enforce
        severity: medium
        object-templates-raw: |
          {{`{{- $pcr8Hash := fromConfigMap "imperative" "initdata" "PCR8_HASH" -}}`}}
          {{`{{- $debugPcr8Hash := fromConfigMap "imperative" "debug-initdata" "PCR8_HASH" -}}`}}
          {{`{{- $rawHash := fromConfigMap "imperative" "initdata" "RAW_HASH" -}}`}}
          {{`{{- $debugRawHash := fromConfigMap "imperative" "debug-initdata" "RAW_HASH" -}}`}}
          {{`{{- $rawHashPadded := printf "%s00000000000000000000000000000000" $rawHash -}}`}}
          {{`{{- $debugRawHashPadded := printf "%s00000000000000000000000000000000" $debugRawHash -}}`}}
          {{`{{- $referenceValues := dict "init_data" (dict "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr8Hash $debugPcr8Hash $rawHash $debugRawHash $rawHashPadded $debugRawHashPadded)) -}}`}}
          {{`{{- $pcrStash := (lookup "v1" "Secret" "trustee-operator-system" "pcr-stash") -}}`}}
          {{`{{- if $pcrStash -}}`}}
          {{`{{- $secretData := $pcrStash.data.json | base64dec | fromJson -}}`}}
          {{`{{- $pcr03 := $secretData.measurements.sha256.pcr03 -}}`}}
          {{`{{- $pcr09 := $secretData.measurements.sha256.pcr09 -}}`}}
          {{`{{- $pcr11 := $secretData.measurements.sha256.pcr11 -}}`}}
          {{`{{- $pcr12 := $secretData.measurements.sha256.pcr12 -}}`}}
          {{`{{- $referenceValues = set $referenceValues "snp_pcr03" (dict "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr03)) -}}`}}
          {{`{{- $referenceValues = set $referenceValues "tdx_pcr03" (dict "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr03)) -}}`}}
          {{`{{- $referenceValues = set $referenceValues "snp_pcr08" (dict "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr8Hash $debugPcr8Hash)) -}}`}}
          {{`{{- $referenceValues = set $referenceValues "tdx_pcr08" (dict "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr8Hash $debugPcr8Hash)) -}}`}}
          {{`{{- $referenceValues = set $referenceValues "snp_pcr09" (dict "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr09)) -}}`}}
          {{`{{- $referenceValues = set $referenceValues "tdx_pcr09" (dict "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr09)) -}}`}}
          {{`{{- $referenceValues = set $referenceValues "snp_pcr11" (dict "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr11)) -}}`}}
          {{`{{- $referenceValues = set $referenceValues "tdx_pcr11" (dict "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr11)) -}}`}}
          {{`{{- $referenceValues = set $referenceValues "snp_pcr12" (dict "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr12)) -}}`}}
          {{`{{- $referenceValues = set $referenceValues "tdx_pcr12" (dict "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr12)) -}}`}}
          {{`{{- end -}}`}}
          {{`{{- $firmwareStash := (lookup "v1" "Secret" "trustee-operator-system" "firmware-reference-values") -}}`}}
          {{`{{- if $firmwareStash -}}`}}
          {{`{{- $firmwareData := $firmwareStash.data.json | base64dec | fromJson -}}`}}
          {{`{{- if $firmwareData.mr_td -}}`}}
          {{`{{- $referenceValues = set $referenceValues "mr_td" (dict "expiration" "2027-12-12T00:00:00Z" "value" $firmwareData.mr_td) -}}`}}
          {{`{{- end -}}`}}
          {{`{{- if $firmwareData.rtmr_1 -}}`}}
          {{`{{- $referenceValues = set $referenceValues "rtmr_1" (dict "expiration" "2027-12-12T00:00:00Z" "value" $firmwareData.rtmr_1) -}}`}}
          {{`{{- end -}}`}}
          {{`{{- if $firmwareData.rtmr_2 -}}`}}
          {{`{{- $referenceValues = set $referenceValues "rtmr_2" (dict "expiration" "2027-12-12T00:00:00Z" "value" $firmwareData.rtmr_2) -}}`}}
          {{`{{- end -}}`}}
          {{`{{- if $firmwareData.snp_launch_measurement -}}`}}
          {{`{{- $referenceValues = set $referenceValues "snp_launch_measurement" (dict "expiration" "2027-12-12T00:00:00Z" "value" $firmwareData.snp_launch_measurement) -}}`}}
          {{`{{- end -}}`}}
          {{`{{- if $firmwareData.xfam -}}`}}
          {{`{{- $referenceValues = set $referenceValues "xfam" (dict "expiration" "2027-12-12T00:00:00Z" "value" $firmwareData.xfam) -}}`}}
          {{`{{- end -}}`}}
          {{`{{- end -}}`}}
          - complianceType: mustonlyhave
            objectDefinition:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: rvps-reference-values
                namespace: trustee-operator-system
              data:
                reference_value: '{{`{{ toJson $referenceValues }}`}}'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: rvps-placement-binding
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "6"
placementRef:
  name: rvps-placement-rule
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: rvps-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: rvps-placement-rule
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchLabels:
      local-cluster: "true"
---
{{ end }}